[tool.poetry]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["peaky76 <robertjamespeacock@gmail.com>"]
license = "GPL-3.0-only"
readme = "README.md"
packages = [{include = "python_template"}]

[tool.poetry.dependencies]
python = "^3.11"


[tool.poetry.group.dev.dependencies]
auto-changelog = "^0.6.0"
black = "^23.7.0"
coverage = "^7.3.0"
mypy = "^1.5.1"
pytest = "^7.4.1"
pytest-cov = "^4.1.0"
ruff = "^0.0.287"
sphinx = "^7.2.5"
sphinx-rtd-theme = "^1.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
